/**
 * This file was automatically generated by tools/generators/generate-cache-file.js file
 */
import { statorApi } from "../stator-api"

export const addPathsCacheKeys = () =>
  statorApi.enhanceEndpoints({
    endpoints: {
      watchPaths: { providesTags: ["paths"] },
    },
  })
export const addGeneratedCacheKeys = () => {
  addPathsCacheKeys()
}
